### ISSUE TITLE
No Update in File-Path for Loading Profiling Table

### ISSUE THREAD

**Issue by ghost** [hpcclab/E2C-Sim#10]
When loading a profiling table, the file-path is not updated from the default.
The same action with the workload does update the filepath from the default.

![image](https://user-images.githubusercontent.com/116416165/223283839-eb2ffc03-1479-4339-b19a-09a309b9de2f.png)

**Comment by Ali-Mokhtari** [comment]
The issue has been resolved in commit fixed path to etc upon loading etc file (255d3d98841593f3cd8d90ea202ccea399dbae5e).
